version: "3"
services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - webnet

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - webnet

networks:
  webnet:




