version: "3"
services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
    volumes:
      - ./postgres-db:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    networks:
      - webnet

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - webnet

networks:
  webnet:




